# This file was generated by GoReleaser. DO NOT EDIT.
class Hikeshi < Formula
  desc "Hikeshi is a security incident response application that keeps documenting incidents simple, so you can focus on fighting fires."
  homepage "https://github.com/brittonhayes/hikeshi"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brittonhayes/hikeshi/releases/v0.0.4/hikeshi_0.0.4_darwin_amd64.tar.gz"
    sha256 "6a5b362cf1fe20d512d57d08279afacac4a92422fe2ca43cb3455c4cdb175eb1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/hikeshi/releases/v0.0.4/hikeshi_0.0.4_linux_amd64.tar.gz"
      sha256 "26e5bc7dd077530a27db9c552fe034057e2b06d68e0a8c34bc5c2662ad0b6a8c"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "hikeshi"
  end

  def caveats; <<~EOS
    hikeshi --help
  EOS
  end
end
