# This file was generated by GoReleaser. DO NOT EDIT.
class Hikeshi < Formula
  desc "Hikeshi is a security incident response application that keeps documenting incidents simple, so you can focus on fighting fires."
  homepage "https://github.com/brittonhayes/hikeshi"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/brittonhayes/hikeshi/releases/v0.1.4/hikeshi_0.1.4_darwin_amd64.tar.gz"
    sha256 "d48b5d8dfa09c396af9e295d73575dba722156398954bf9c3652d5377bae8db7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/brittonhayes/hikeshi/releases/v0.1.4/hikeshi_0.1.4_linux_amd64.tar.gz"
      sha256 "b4ff9ced00603e1cbe75df5dde51e1a052d023193d2d838e1dc92681b860e537"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional

  def install
    bin.install "hikeshi"
  end

  def caveats; <<~EOS
    hikeshi --help
  EOS
  end
end
